# Generated by Django 4.1.2 on 2022-10-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boardgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('producer', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=200)),
                ('issue_year', models.CharField(max_length=10)),
                ('min_age_of_player', models.PositiveSmallIntegerField()),
                ('min_number_of_players', models.PositiveSmallIntegerField()),
                ('max_number_of_players', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
