# Generated by Django 4.1.2 on 2022-10-16 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardgameAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('producer', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=200)),
                ('issue_year', models.CharField(max_length=10)),
                ('min_number_of_players', models.PositiveSmallIntegerField()),
                ('max_number_of_players', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('min_age_of_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boardgames.boardgameage')),
            ],
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='min_age_of_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boardgame', to='boardgames.boardgameage'),
        ),
    ]
